# common fragment for Makefile and Makefile.msvc containing the list of source files and folders

# set up folder names
SRCDIR    = src
OBJDIR    = obj
EXEDIR    = exe
TESTSDIR  = tests
TORUSDIR  = src/torus

# sources of the main library
SOURCES   = interface_c.cpp \
            interface_fortran.cpp \
            interface_nemo.cpp \
            interface_python.cpp \
	    math_core.cpp \
            math_fit.cpp \
            math_gausshermite.cpp \
            math_geometry.cpp \
            math_linalg.cpp \
            math_ode.cpp \
	    math_optimization.cpp \
            math_random.cpp \
            math_sample.cpp \
            math_specfunc.cpp \
            math_sphharm.cpp \
            math_spline.cpp \
            particles_io.cpp \
            actions_factory.cpp \
            actions_focal_distance_finder.cpp \
            actions_isochrone.cpp \
            actions_spherical.cpp \
            actions_staeckel.cpp \
            actions_torus.cpp \
            coord.cpp \
            df_base.cpp \
            df_disk.cpp \
            df_factory.cpp \
            df_halo.cpp \
            df_spherical.cpp \
            galaxymodel_base.cpp \
            galaxymodel_densitygrid.cpp \
            galaxymodel_fokkerplanck.cpp \
            galaxymodel_jeans.cpp \
            galaxymodel_losvd.cpp \
            galaxymodel_selfconsistent.cpp \
            galaxymodel_spherical.cpp \
            galaxymodel_velocitysampler.cpp \
            orbit.cpp \
            orbit_variational.cpp \
            potential_analytic.cpp \
            potential_base.cpp \
            potential_composite.cpp \
            potential_cylspline.cpp \
            potential_dehnen.cpp \
            potential_disk.cpp \
            potential_factory.cpp \
            potential_ferrers.cpp \
	    potential_interpolators.cpp \
            potential_king.cpp \
            potential_multipole.cpp \
            potential_perfect_ellipsoid.cpp \
            potential_spheroid.cpp \
            potential_utils.cpp \
            raga_core.cpp \
            raga_binary.cpp \
            raga_losscone.cpp \
            raga_potential.cpp \
            raga_relaxation.cpp \
            raga_trajectory.cpp \
            utils.cpp \
            utils_config.cpp \

# ancient Torus code
TORUSSRC  = CHB.cc \
            Fit.cc \
            Fit2.cc \
            GeneratingFunction.cc \
            Orb.cc \
            PJMNum.cc \
            Point_ClosedOrbitCheby.cc \
            Point_None.cc \
            Torus.cc \
            Toy_Isochrone.cc \
            WD_Numerics.cc \

# test and example programs
TESTSRCS  = test_galaxymodel.cpp \
            example_actions_nbody.cpp \
            example_df_fit.cpp \
            example_doublepowerlaw.cpp \
            example_self_consistent_model.cpp \
            example_self_consistent_model_mw.cpp \

#TESTFORTRAN = test_fortran.f
            
